### ISSUE TITLE
Django 2.0 support

### ISSUE THREAD

**Issue by vmspike** [edoburu/django-private-storage#16]
django-private-storage 1.2.3 is incompatible with Django 2.0 yet, while Django 2.0 already exists in some repo files it can mislead some users.

Specific incompatibilities I've found:
 - in `permissions.py`
> Using User.is_authenticated() and User.is_anonymous() as methods rather than properties is no longer supported.
- in `fields.py`
> FileField methods get_directory_name() and get_filename() are removed.

I could miss something else.

Hope you're going to add support of Django 2.0 soon.

**Comment by vdboor** [comment]
Hi! Thanks for letting us know!

Since - unlike us - you're already using this package in Django 2.0, would you be so kind to provide a pull request for it? We can merge that, and release a new version. Please make sure the pull requests keeps compatibility with older Django versions.

**Comment by vdboor** [comment]
Thanks, I've merged the commit!

**Comment by vdboor** [comment]
Could you also test the latest master? I've updated `generate_filename()` to reflect the modern Djagno behavior much better.

**Comment by vdboor** [comment]
Update, after writing unit tests I've released v2.0 :-)

**Comment by gil-obradors** [comment]
I'm new, I think in django 2.x url function from django.urls is replaced by re_path
...to specify at README.rst
