### ISSUE TITLE
How exactly is `max_file_size` used?

### ISSUE THREAD

**Issue by pritstift** [edoburu/django-private-storage#19]
How exactly is `max_file_size` used? As i can see from the Traceback it is supposed to be an integer. What unit does it refer to?

Thanks

**Comment by vdboor** [comment]
`max_file_size ` is the size of the file in bytes.

Hence: 1 MB = 1024 * 1024

**Comment by vdboor** [comment]
I've updated the README to clarify this

**Comment by pritstift** [comment]
Great. Thanks
