### ISSUE TITLE
Django REST `is_authenticated` support

### ISSUE THREAD

**Issue by yarsanich** [edoburu/django-private-storage#24]
Hi! Thanks for the very useful package. It saved me a lot of time!

I just would like to suggest to add some django-rest-framework support from the box. 

You have permission function `is_authenticated`, but it is only for Django request, but as I understand DRF has own Request class and own `is_authenticated`.

I found a workaround for support.

I just inherited from `APIview` and `PrivateStorageDetailView` and all works fine.

Is it the right way, or maybe there is a more elegant way.

**Comment by vdboor** [comment]
Hi! That is a nice solution, and I'd likely would have done the same. The view is really basic, so it's easy to combine. The `can_access_file` logic is still in effect, but you can override that, or let it return `True` since the DRF already does all authentication.
