### ISSUE TITLE
Download empty files after activate server options for Apache

### ISSUE THREAD

**Issue by cometchaser** [edoburu/django-private-storage#26]
Hi, 

I deployed my Django + Private-Storage page on an Apache server + mod_wsgi combi on a CentOS maschine. Unfortunately, when I set 
`PRIVATE_STORAGE_SERVER = 'apache'`
the downloaded files are all empty.  Does anyone has an idea, what might be wrong?

**Comment by vdboor** [comment]
The Apache feature depends on mod_xsendfile, which seems to be deprecated nowadays.

However, the default behavior likely already sends file efficiently from your server.

**Comment by perstar** [comment]
I think you will get empty files with the development server, so you should only set PRIVATE_STORAGE_SERVER when actually running through Apache. I have

```
if not RUNNING_DEVSERVER:                                                       
    PRIVATE_STORAGE_SERVER = 'apache'
```

using a variable I set early in settings.py and use for different things. Then you must install mod_xsendfile and activate it. In a conf file in /etc/httpd/conf.d I have

```
<virtualhost ...>
  ...
  WSGIScriptAlias / ...
  XSendFileOn
  XSendFilePath ... [path to where the files are, same as PRIVATE_STORAGE_ROOT]
  ...
</virtualhost>
```

I haven't heard of mod_xsendfile being deprecated. And it seems like the Django documentation strongly advises not to send media files through the Django server.

**Comment by cometchaser** [comment]
I missed the part, that the apache module xsendfile is needed for this package. Thanks, now it is working fine.  I
