### ISSUE TITLE
Problem using S3

### ISSUE THREAD

**Issue by lorinkoz** [edoburu/django-private-storage#28]
Testing `PRIVATE_STORAGE_S3_REVERSE_PROXY = True`.
It saves the files properly on S3, yet, when retrieving the file, when it tries to access the django sever view, it gives 404. Do I have to configure a reverse proxy with apache/nginx/caddy or the django server view actually fetches the object from S3 and proxies to the client?

**Comment by lorinkoz** [comment]
I am getting `"/path/to/file" does not exist` which is a different error from using a true unexisting path

**Comment by vdboor** [comment]
Hi, the while point of the `PRIVATE_STORAGE_S3_REVERSE_PROXY` is to let Django retrieve the file, and serve it. Thus, Django becomes a proxy for the S3 file. I can't really diagnose what's happening here. Maybe some bucket policy prevents the file from being downloaded? For some reason Django doesn't seem to be able to fetch the file.

**Comment by lorinkoz** [comment]
From the same server, I can do `TargetModel.objects.get(....).private_file_field.read()`. Any clues why django won't be able to fetch it from S3?

**Comment by lorinkoz** [comment]
Can you help me debug this? From the error, is this a `private-storage` error or something passed by `boto`?

**Comment by lorinkoz** [comment]
Possible problem:
In django, I am hosting the reverse proxy on the url `/file/...`
In the S3 bucket, the `file` folder does not exist.
Assuming `private_file` is an instance of a private file, if I do:
`private_file.storage.exists(private_file.path)` it raises `SuspiciousOperation`, as `path` is prefixed with `/file`. Then, if I manually remove the `/file` part, the storage returns `True`.
As I said before, I can `private_file.read()` and `private_file.size` without any problem.

**Comment by lorinkoz** [comment]
The error seems to be raised by Django's `serve`.

```
if not fullpath.exists():
        raise Http404(_('"%(path)s" does not exist') % {'path': fullpath})
```

What I am puzzled about is that I don't see how Django's `serve` can handle S3 files, while checking existence against a `pathlib` (thus local) path.

**Comment by lorinkoz** [comment]
@vdboor Sorry to prod, any clues here?
