### ISSUE TITLE
Grab file for manual handling

### ISSUE THREAD

**Issue by lorinkoz** [edoburu/django-private-storage#33]
I am using this package in reverse proxy mode, against an S3 bucket. I need to manually get an image from the storage in order to put it in a PDF with reportlab. My fetching function looks like:

    def fetch_image(private_image):
        from io import BytesIO
        from PIL import Image
        import requests

        response = requests.get(private_image.url)
        return Image.open(BytesIO(response.content))

`private_image.url` responds with the reverse-proxied url, it's not working for me as I have other checks in place.

I need the actual url of the file, or the actual path of the file, or anything that helps me retrieve the image from the underlying storage. How can I do it?

**Comment by vdboor** [comment]
You'll have to use the standard Django storage API's. Something like:

```
with private_image.open() as f:
  data = f.read()
```
