### ISSUE TITLE
Incompatibility with Django 3

### ISSUE THREAD

**Issue by wiegandm** [edoburu/django-private-storage#41]
First, thank you very much for this great plugin!

While testing the deployment of an app using `django-private-storage` in an environment with the recently release Django 3.0, I noticed that `django-private-storage` attempts to import `django.utils.six` in `fields.py`.

As Django 3.0 has removed private Python 2 compatibility APIs like `django.utils.six`, trying to import it raises a `ModuleNotFoundError`.

See https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis for details; the Django release notes suggest to either remove usage of this vendored library or switching to using six directly.

**Comment by wiegandm** [comment]
I have created two PRs (#42 and #45) which should address this issue -- more
specifically, a tox test matrix built on the changes in #43 also succeeds for
Django 3.0.

Merging both #42 and #45 would make django-private-storage work
with Django 3 (AFAICT, at least the unit tests succeed), but at the
price of losing compatibility with Python 2.7.

I leave it up to the maintainers of this fine project to make the decision, but
in my humble opinion, supporting Django 3.0 would be preferable to supporting
Python 2.7 past the upcoming EOL.

**Comment by chekroA** [comment]
Hi @vdboor ! Thank you for maintaining this project so far. I would like to use `django-private-storage`  with Django 3. Is it possible to validate the #42 and #45 soon ? Thank you :smile_cat:

**Comment by winsmith** [comment]
I forked @wiegandm's repo and merged the two PRs in there. If you want to play around with it (on your computer, not in production), you can use this entry in your `requirements.txt` to install the patched version of `django-private-storage`:

```
# This fixes an incompatibility with Django 3. Once the following PRs are merged, go back to the original django-private-storage package:
# 42 https://github.com/edoburu/django-private-storage/pull/42
# 45 and https://github.com/edoburu/django-private-storage/pull/45
git+https://github.com/winsmith/django-private-storage.git@master#egg=django-private-storage
```

**Comment by vdboor** [comment]
Django 3.0 support is fixed in 2.2.2! I've used your PR's as inspiration, but implemented it in a python2 compatible way so I could do a minor version bump instead of major release that drops compatibility.

**Comment by wiegandm** [comment]
Thanks a lot!

**Comment by chekroA** [comment]
Thank you

**Comment by winsmith** [comment]
Woohoo thanks so much!
