### ISSUE TITLE
ModuleNotFoundError: No module named 'django.utils.six'

### ISSUE THREAD

**Issue by AlbertDavid94** [edoburu/django-private-storage#48]
Hi, today I got the following error:
`File: /usr/lib/python3.8/site-packages/private_storage/fields.py`, line 16, in <module>
from django.utils.six import string_types
ModuleNotFoundError: No module named 'django.utils.six'

I've got auto-updates on my machine and a reboot caused this error to pop up. 

I have Django 3.0.2 installed

sorry, I just realised it's a duplicate of #41

**Comment by vdboor** [comment]
No problem, thanks for mentioning it! I've released v2.2.2 with Django 3.0 compatibility.
