### ISSUE TITLE
upload_subfolder error

### ISSUE THREAD

**Issue by javialon26** [edoburu/django-private-storage#5]
Hello i have a problem with upload_subfolder because the folder is not created correctly.

settings
INSTALLED_APPS += (
    'private_storage',
)
PRIVATE_STORAGE_ROOT = str(APPS_DIR('protectedfiles')) #/api/protectedfiles/
PRIVATE_STORAGE_AUTH_FUNCTION = 'private_storage.permissions.allow_staff'

urls:
import private_storage.urls
url(r'^downloads/private/', include(private_storage.urls)),

model:
def dni_dir_path(instance):
    return 'user_{0}'.format(str(instance.id))

upload_dni = PrivateFileField(
    'documento',
    upload_subfolder=dni_dir_path,
    blank=True
 )

I'm uploading the file from django admin, everything works perfect but the file is uploaded to:
/api/protectedfiles/u/s/e/r/_/1/Test-Disease-List.json instead:
/api/protectedfiles/user_1/Test-Disease-List.json

i'm running django==1.10.7, python 2.7.13 with docker

Thank you!

**Comment by vdboor** [comment]
The `dni_dir_path` function should return a list (so it joins path elements itself). The string is now interpreted as such.

**Comment by vdboor** [comment]
Fixed in v2.0!
