### ISSUE TITLE
adjust to django-storages 1.10.1

### ISSUE THREAD

**Issue by patroqueeet** [edoburu/django-private-storage#61]
as of now it fails with an exception when using latest django storages

**Comment by tomturner** [comment]
I have created a version that seem to work woth the new version of django-storages

https://github.com/tomturner/django-private-storage/tree/fix-boto-issue

I haven't made it backwards compatible so at the moment I not doing a pull request.

**Comment by ab-smith** [comment]
hi, will this be merged at some point?

**Comment by vdboor** [comment]
#64 was merged!

@tomturner the PR used a different approach then your branch did. Do you expect any issues with either solution?
