### ISSUE TITLE
Serve files that weren't uploaded via Django Admin/API

### ISSUE THREAD

**Issue by philshem** [edoburu/django-private-storage#63]
This tool is doing almost what I need, but I'd like to be able to serve static (PDF) files with the private-storage folder without uploading via the Django API or website. (e.g. `rsync` files from another machine)

I've tried to put files into the private-storage folder, but they don't show up in the admin dashboard. Is it possible to just serve whatever is in the folder?

**Comment by rmortes** [comment]
Maybe you could have an AWS lambda that detects when a new file is uploaded to the bucket and sends a request to your server notifying it

**Comment by philshem** [comment]
In the end, I created a new model for the files, and then created the objects (with metadata as fields) with a code based on this snippet:

https://gist.github.com/bsnux/4952342
