### ISSUE TITLE
django 4.1 compatibility

### ISSUE THREAD

**Issue by webcircles-franco** [edoburu/django-private-storage#79]
Hello, 

on django 4.1 i get this error

`was_modified_since() takes from 0 to 2 positional arguments but 3 were given
`

i think the problem is here

` def serve(private_file):
        # Support If-Last-Modified
        mtime = private_file.modified_time.timestamp()
        size = private_file.size
        if not was_modified_since(private_file.request.META.get('HTTP_IF_MODIFIED_SINCE'), mtime, size):
            return HttpResponseNotModified()`

here the reference of django changelog https://docs.djangoproject.com/en/4.1/releases/4.1/#miscellaneous

**Comment by Real-Gecko** [comment]
@edoburu Any news?

**Comment by dpunkturban** [comment]
Would be nice if the package here is Django 4.11 compatible too. It is the only thing that prevents us from updating to Django 4.11.

I have already opened a PR, but nothing has happened yet: #80

**Comment by dpunkturban** [comment]
> Would be nice if the package here is Django 4.1 compatible too. It is the only thing that prevents us from updating to Django 4.1.
> 
> I have already opened a PR, but nothing has happened yet: #80

**Comment by grumpyp** [comment]
Indeed, it would help me a lot in my development! Please merge #80

**Comment by Whitie** [comment]
Please merge #80 for newer projects. In a few month (April 23) Django 4.2 LTS will arrive. A good choice for new projects. So far, thank your for your work.

**Comment by amorilla** [comment]
new release 3.1 updated at PyPi.
