### ISSUE TITLE
Get object that contains PrivateFileField in custom function for permissions

### ISSUE THREAD

**Issue by gregoriopellegrino** [edoburu/django-private-storage#8]
Is it possible to get the object that contains the PrivateFileField requested in custom function for checking permissions?

**Comment by vdboor** [comment]
Yes, if you use a custom view.

You can extend `PrivateStorageDetailView`, and place that in your `urls.py`.
Then, all standard "DetailView" logic can take place, such as whether you may access the object or not (through overriding `get_queryset()`), and you can also override `def can_access_file(self, private_file):`.

**Comment by vdboor** [comment]
I've added an example to the README!
